language: cpp
compiler:
- clang
sudo: required
dist: xenial
cache:
  directories:
  - hptt/lib
before_install:
- cd hptt && make && cd ..
- sudo apt-get install intel-mkl
install:
- make compile
script:
- ./test.out
- ./Heisenberg_MPS_SU.out -L4 -D4
env:
  global:
    - MAKEFLAGS="-j 8"
