language: cpp
compiler:
- clang
sudo: required
dist: xenial
cache:
  directories:
  - hptt
before_install:
- sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
- sudo apt-get update && sudo apt-get install -y --allow-unauthenticated intel-mkl-2019.2-057 libjemalloc-dev
- cd hptt && ls lib/libhptt.a lib/libhptt.so || make && cd ..
install:
- make compile
script:
- diff <(./test.out) ./test.stdout
- diff <(./Heisenberg_MPS_SU.out -L4 -D4 | tail -n 2 | head -n 1) <(cat ./Heisenberg_MPS_SU.stdout| tail -n 2 | head -n 1)
- ! (diff <(./Heisenberg_MPS_SU.out -L4 -D4 | tail -n 1 | python -m json.tool) <(cat ./Heisenberg_MPS_SU.stdout | tail -n 1 | python -m json.tool) -y | grep -v "addr" | grep "|")
env:
  global:
    - MAKEFLAGS="-j 8"
