os: linux
dist: xenial
language: cpp
matrix:
  fast_finish: true
  include:
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - g++-5
        - libjemalloc-dev
        - --allow-unauthenticated intel-mkl-2019.2-057
    env:
    - MATRIX_EVAL="CXX=g++-5"
    compiler: gcc-5
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - g++-6
        - libjemalloc-dev
        - --allow-unauthenticated intel-mkl-2019.2-057
    env:
    - MATRIX_EVAL="CXX=g++-6"
    compiler: gcc-6
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - g++-7
        - libjemalloc-dev
        - --allow-unauthenticated intel-mkl-2019.2-057
    env:
    - MATRIX_EVAL="CXX=g++-7"
    compiler: gcc-7
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - g++-8
        - libjemalloc-dev
        - --allow-unauthenticated intel-mkl-2019.2-057
    env:
    - MATRIX_EVAL="CXX=g++-8"
    compiler: gcc-8
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-5
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - clang-5
        - libjemalloc-dev
        - --allow-unauthenticated intel-mkl-2019.2-057
    env:
    - MATRIX_EVAL="CXX=clang++-5"
    compiler: clang-5
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-6
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - clang-6
        - libjemalloc-dev
        - --allow-unauthenticated intel-mkl-2019.2-057
    env:
    - MATRIX_EVAL="CXX=clang++-6"
    compiler: clang-6
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-7
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - clang-7
        - libjemalloc-dev
        - --allow-unauthenticated intel-mkl-2019.2-057
    env:
    - MATRIX_EVAL="CXX=clang++-7"
    compiler: clang-7
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - clang-8
        - libjemalloc-dev
        - --allow-unauthenticated intel-mkl-2019.2-057
    env:
    - MATRIX_EVAL="CXX=clang++-8"
    compiler: clang-8
cache:
  directories:
  - hptt
before_install:
- eval "${MATRIX_EVAL}"
- cd hptt
- ls lib/libhptt.a lib/libhptt.so || make
- cd ..
install:
- make compile
script:
#- diff <(./test.out) ./test.stdout
- diff <(./Heisenberg_MPS_SU.out -L4 -D4 | tail -n 2 | head -n 1) <(cat ./Heisenberg_MPS_SU.stdout| tail -n 2 | head -n 1)
- diff <(./Heisenberg_MPS_SU.out -L4 -D4 | tail -n 1 | python -m json.tool | grep -v addr) <(cat ./Heisenberg_MPS_SU.stdout | tail -n 1 | python -m json.tool | grep -v addr)
- ./Heisenberg_MPS_SU.out -L4 -D4
- ./Heisenberg_MPS_SU_env.out
- ./test.out
env:
  global:
    - MAKEFLAGS=-j8
notifications:
  email: false
