language: cpp
compiler:
- clang
os:
- linux
cache:
  directories:
  - hptt/lib
before_install:
- cd hptt && make && cd ..
install:
- make compile
script:
- ./test.out
- ./Heisenberg_MPS_SU.out -L4 -D4
env:
  global:
    - MAKEFLAGS="-j 8"
