os: linux
dist: xenial
language: cpp
matrix:
  fast_finish: true
  include:
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-7
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - g++-9
        - clang-7
        - libomp-dev
        - --allow-unauthenticated intel-mkl-2019.4-070
    env:
    - MATRIX_EVAL="CXX=\"clang++-7 -I/usr/include/c++/9\""
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-xenial-8
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - g++-9
        - clang-8
        - libomp-dev
        - --allow-unauthenticated intel-mkl-2019.4-070
    env:
    - MATRIX_EVAL="CXX=\"clang++-8 -I/usr/include/c++/9\""
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - g++-7
        - libomp-dev
        - --allow-unauthenticated intel-mkl-2019.4-070
    env:
    - MATRIX_EVAL="CXX=g++-7"
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - g++-8
        - libomp-dev
        - --allow-unauthenticated intel-mkl-2019.4-070
    env:
    - MATRIX_EVAL="CXX=g++-8"
  - addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: deb https://apt.repos.intel.com/mkl all main
        packages:
        - g++-9
        - libomp-dev
        - --allow-unauthenticated intel-mkl-2019.4-070
    env:
    - MATRIX_EVAL="CXX=g++-9"
cache:
  directories:
  - deps/hptt
before_install:
- eval "${MATRIX_EVAL}"
- cd deps/hptt
- ls lib/libhptt.a || mkdir lib && cd lib && cmake .. && make && cd ..
- cd ../..
install:
- mkdir -p build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Debug
- make VERBOSE=1
script:
- ./lazy.out
- ./test.out
- ./Heisenberg_MPS_SU.out -L4 -D4
env:
  global:
    - MAKEFLAGS=-j
    - MKLROOT=/opt/intel/compilers_and_libraries/linux/mkl
notifications:
  email: false
