os: linux
dist: bionic
language: cpp
addons:
  apt:
    update: true
    packages:
    - clang-7
    - g++-7
    - libomp-dev
    - libopenblas-dev
    - liblapacke-dev
matrix:
  fast_finish: true
  include:
  - env:
    - MATRIX_EVAL="CXX=clang++-7"
  - env:
    - MATRIX_EVAL="CXX=g++-7"
cache:
  directories:
  - deps/hptt
before_install:
- eval "${MATRIX_EVAL}"
- cd deps/hptt
- ls lib/libhptt.a || mkdir lib && cmake -DHPTT_CXX_FLAGS=-Ofast -DENABLE_AVX=ON -H. -Blib && cmake --build lib --parallel
- cd ../..
install:
- wget https://raw.githubusercontent.com/xianyi/OpenBLAS/66ac898f6441f0cb334f76d0c5603c37962bf368/cblas.h -O include/cblas.h
- sed -i s/common.h/openblas_config.h/ include/cblas.h
- mkdir -p build
- cmake .. -DCMAKE_BUILD_TYPE=Release -H. -Bbuild
- cmake --build build --parallel
script:
- cmake --build build --target test
notifications:
  email: false
