dist: xenial
sudo: required
language: cpp
cache:
  directories:
  - hptt
addons:
  apt:
    sources:
    - sourceline: deb https://apt.repos.intel.com/mkl all main
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-8
    update: true
    packages:
    - g++-8
    - clang-8
    - libjemalloc-dev
    - --allow-unauthenticated intel-mkl-2019.2-057
before_install:
- cd hptt
- ls lib/libhptt.a lib/libhptt.so || make -j8 CXX=clang++-8
- cd ..
- pip install --user cpp-coveralls
install:
- make compile -j8 DEBUG=1 CXX=clang++-8
script:
# - diff <(./test.out) ./test.stdout
- diff <(./Heisenberg_MPS_SU.out -L4 -D4 | tail -n 2 | head -n 1) <(cat ./Heisenberg_MPS_SU.stdout| tail -n 2 | head -n 1)
- diff <(./Heisenberg_MPS_SU.out -L4 -D4 | tail -n 1 | python -m json.tool | grep -v addr) <(cat ./Heisenberg_MPS_SU.stdout | tail -n 1 | python -m json.tool | grep -v addr)
- ./Heisenberg_MPS_SU.out -L4 -D4
- ./Heisenberg_MPS_SU_env.out
- ./test.out
after_success:
- coveralls --exclude args --exclude rang --exclude cutt --exclude hptt --gcov `which gcov-8`
notifications:
  email: false
