package:
  name: tetragono
  version: 0.1.4

source:
  url: https://github.com/hzhangxyz/TAT/archive/refs/heads/dev.zip
  extras:
    - [setup.py, setup.py]

requirements:
  run:
    - lazy
    - TAT
    - numpy
    - CLAPACK
