name: build

on: [push, pull_request]

jobs:

  create_release:
    name: create github release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: recovery tag information
        run: git fetch --tags --force
        # See: https://github.com/actions/checkout/issues/290
      - name: check tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ '^refs/tags/v[0-9]+(\.[0-9]+)*a1$' ]]; then
              echo "match=true"
              echo "match=true" >> $GITHUB_OUTPUT
          else
              echo "match=false"
          fi
      - name: release
        if: steps.check-tag.outputs.match == 'true'
        run: |
          echo try to release
