name: check

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-20.04
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install mpi and openblas
      run: sudo apt-get install -y mpi-default-dev libopenblas-serial-dev
    - name: make build directory
      run: mkdir ${{runner.workspace}}/build
    - name: configure
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{github.workspace}}
    - name: ctest
      working-directory: ${{runner.workspace}}/build
      run: ctest -E ^test_\(svd\|qr\)$
