name: check

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: directory
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE
    - name: make
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .
    - name: test
      working-directory: ${{runner.workspace}}/build
      run: ctest --verbose
