name: doxygen

on:
  push:
    branches:
    - TAT

jobs:
  doxygen:

    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: find tag
      id: tagger
      uses: digital-ai/query-tag-action@v2
    - name: update version
      run: sed -i s/dev/${{steps.tagger.outputs.tag}}/ Doxyfile
    - name: install doxygen
      run: sudo apt-get install doxygen -y
    - name: create docs
      run: doxygen
    - name: publish
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
